server:
  port: 0
endpoints:
  shutdown:
    enabled: true
spring:
  main:
    show_banner: false
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
  yarn:
    applicationBaseDir: ${deployer.yarn.app.baseDir:/dataflow}/apps/task/
    appmaster:
      containerCount: 1
      appmasterClass: org.springframework.cloud.deployer.spi.yarn.tasklauncher.TaskAppmaster
      localizer:
        patterns:
          - "servers.yml"
      resource:
        priority: ${deployer.yarn.app.taskcontainer.priority:10}
        labelExpression: ${deployer.yarn.app.taskcontainer.labelExpression:}
        memory: ${deployer.yarn.app.taskcontainer.memory:256m}
        virtualCores: ${deployer.yarn.app.taskcontainer.virtualCores:1}
      launchcontext:
        options:
          - ${deployer.yarn.app.taskcontainer.javaOpts:}
        arguments:
          -Dserver.port: 0
          -Dspring.jmx.enabled: false              
          -Dspring.config.location: servers.yml
        locality: false
    endpoints:
      containerregister:
        enabled: false
