logging:
  level:
    org.springframework.cloud.dataflow.module.deployer.yarn: DEBUG
    org.springframework.statemachine: DEBUG
spring:
  main:
    show_banner: false
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
  yarn:
    appType: DATAFLOW
    appName: scdstream:app
    applicationBaseDir: /dataflow/apps/stream/
    client:
      clientClass: org.springframework.yarn.client.DefaultApplicationYarnClient
      files:
        - "file:${dataflow.yarn.app.appmaster.path:lib}/spring-cloud-deployer-yarn-appdeployerappmaster-*.jar"
        - "file:${dataflow.yarn.app.config.path:config}/servers.yml*"
      queue: ${dataflow.yarn.app.streamappmaster.queue:default}
      labelExpression: ${dataflow.yarn.app.streamappmaster.labelExpression:}
      launchcontext:
        arguments:
          -Dspring.config.location: servers.yml
        archiveFile: spring-cloud-deployer-yarn-appdeployerappmaster-${spring.cloud.dataflow.yarn.deployerversion}.jar
      localizer:
        patterns:
          - "spring-cloud-deployer-yarn-appdeployerappmaster-*.jar"
          - "servers.yml"
      resource:
        memory: ${dataflow.yarn.app.streamappmaster.memory:512m}
        virtualCores: ${dataflow.yarn.app.streamappmaster.virtualCores:1}
